spring:
  security:

    # authentication
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken%40system.gserviceaccount.com
          issuer-uri: https://securetoken.google.com/budget-c1ab6
          jws-algorithm: RS256

  # database access
  datasource:
    url: jdbc:h2:./liquibase;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ''
  liquibase:
    change-log: 'classpath:db/changelog/db.changelog-master.yaml'
  jpa:
    hibernate:
      ddl-auto: update
