spring:
  security:

    # authentication
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken%40system.gserviceaccount.com
          issuer-uri: https://securetoken.google.com/budget-auth-71712
          jws-algorithm: RS256

  # database access
  datasource:
    url: jdbc:h2:./liquibase;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ''
  liquibase:
    enabled: true
    change-log: 'classpath:db/changelog/db.changelog-master.yaml'
  jpa:
    hibernate:
      ddl-auto: validate

      # if you want to use liquibase
      # ddl-auto: validate

      # if you want to let spring data update the db schema
      # ddl-auto: update

security:
  cors:
    allowedOrigins: http://localhost:9000
    allowedMethods: GET, POST, PUT
    allowCredentials: true
    allowedHeaders: Content-Type, Access-Control-Request-Method, Access-Control-Allow-Credentials, Access-Control-Allow-Origin, Access-Control-Allow-Headers, x-requested-with, Authorization, origin, accept
